name: Angular CI/CD with Firebase

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for Angular)
        uses: actions/setup-node@v4
        with:
          node-version: 11  # Keep Node 11 for Angular build

      - name: Install Dependencies
        run: npm install  # Ensures a clean installation of dependencies

      - name: Build Angular App
        run: npm run build # Production build

      - name: Setup Node.js (for Firebase Deployment)
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Switch to Node 20 for Firebase deployment

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live  # Deploy to live channel
          projectId: your-firebase-project-id  # Replace with your Firebase project ID
